### ISSUE TITLE
Heavy Memory usage up to 11GB

### ISSUE THREAD

**Issue by diegopacheco** [signalfx/signalfx-collectd-plugin#59] opened 2017-11-02 18:53 UTC
Hi All,

Before 0.29 we were experiencing heavy memory usage up to 4GB. Now we have a machine using version: 0.0.32. This machine has *11GB* virtual memory for collectd process.  Looks like the memory leak still there. Could you guys take a look? 

Same information
==============

* Running on EC2 AWS-LINUX
* R3 box with 30GB of ram.
* The issue happen last Friday on 27th October.

Version
```bash
Verify version: cat /opt/signalfx-collectd-plugin/signalfx_metadata.py | grep VERSION | head -n 1
VERSION = "0.0.32"
```

Memory
```bash
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                          
30240 root      20   0 11.2g 213m  26m S  3.3  0.7   4:05.70 collectd 
```
SignalFC CollectD log
```bash
stance = host_mem_total, type = objects, type_instance = host-meta-data, message = 31417376
[2017-11-02 00:55:13] signalfx-metadata: till next metadata 86987.9999981 seconds
[2017-11-02 07:22:07] signalfx-metadata: unsuccessful response: <urlopen error _ssl.c:478: The handshake operation timed out>
[2017-11-02 07:37:36] signalfx-metadata: unsuccessful response: <urlopen error _ssl.c:478: The handshake operation timed out>
[2017-11-02 14:50:16] write_http plugin: HTTP Error code: 0
[2017-11-02 14:50:16] write_http plugin: curl_easy_perform failed with status 28: Operation timed out after 3001 milliseconds with 0 bytes received
[ec2-user@ip-172-30-199-77 signalfx-collectd-plugin]$ 
```

**Comment by mpetazzoni** [comment] 2017-11-06 05:22
Hi @diegopacheco,

Could you share the list of plugins that is configured in your collectd? If you think it's caused by the signalfx collectd plugin (this repo), could you isolate to just that plugin (and the `write_http` plugin) to confirm it is, in fact, the source of the memory leak?

That being said, a quick glance at the code and I can already tell that https://github.com/signalfx/signalfx-collectd-plugin/blob/master/src/signalfx_metadata.py#L285 is probably wrong and should just be `if self.metrics[t]`.

**Comment by codesmith14** [comment] 2017-11-06 18:00
Hi @diegopacheco,

I noticed connectivity issues in the log snippet that you shared.  Could you please open a support ticket through [support.signalfx.com](https://support.signalfx.com) and share your configuration files and logs for this host?  We would like to take a closer look at the issue.  Please provide a link to this github issue in the support ticket.

Thank you!

**Comment by diegopacheco** [comment] 2017-11-06 18:30
@mpetazzoni 

This is a long time issue. Since for 0.29 we are experience Collected using lots of memory. We thought this was fixed at 0.30. Here are all plugins I'm using for this host:
```bash
10-aggregation-cpu.conf  
10-jmx.conf  
10-signalfx.conf  
10-write_http-plugin.conf  
11-redis.conf  
12-rocksdb.conf  
20-javageneric.conf
```
But looks like you already find the culprit - when can you guys release a fix?

**Comment by diegopacheco** [comment] 2017-11-06 18:32
@charliesignalfx 

Done. Here is the issue: https://support.signalfx.com/hc/en-us/requests/3576

**Comment by beccatortell** [comment] 2017-11-07 00:10
Hi @diegopacheco,

Thanks for providing the additional info. Engineering has taken a closer look at the issue, and we think what you're seeing is not a memory leak, but rather the normally high level associated with the JMX plugin. 

We checked for a leak in resource consumption on this plugin using our own long-running test environment, and observed that virtual memory usage of the agent and this plugin on those long-running instances has been consistent, not increasing or accelerating, for over 3 months. We found that virtual memory usage is highest on those test instances that are using JMX-based plugins, at roughly the same value that you reported. You included the JMX plugin in the list of plugins you're using (10-jmx.conf), and we think this is the reason for the high usage you're seeing. 

Our engineer also examined the statement that @mpetazzoni pointed out in his earlier comment. We'd characterize this as an unusual style choice, but not a bug, and not related to the issue you reported. 

Have you observed any sudden changes or increases in resource usage? Is virtual memory usage wildly different across several hosts with the same configuration? If there's anything else we're missing, please let us know and we'll be happy to investigate further.

**Comment by diegopacheco** [comment] 2017-11-07 00:18
@beccatortell 

I found JMX plugin pretty buggy. Some time ago my team were passing by mistake properties of mbeans that does not exist and that make plugin suck lots of rams. A long time ago I talked with one of you QA Engineer "RAM" and  I asked him if he had something to valid JMX collectD config in order to avoid this - he said was not aware of the problem.  So whats the fix them?

**Comment by beccatortell** [comment] 2017-11-07 23:09
Hi @diegopacheco,

It's typical in our test environments to see this level of high virtual memory usage associated with the collectd-java plugin. This is not a leak, but rather the expected behaviour of collectd-java.

Because the issue you're seeing is not related to the SignalFx metadata plugin, I'm going to close this issue and continue the conversation over in the Support ticket that you filed with us. Thanks for reporting it.

**Closed as completed by beccatortell** 2017-11-07 23:09 UTC
Labels: bug, question
